// Decompiled with JetBrains decompiler
// Type: TRCC.DCUserControl.UCDongHuaLianDong
// Assembly: TRCC, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null
// MVID: CB0A5FF9-0AB9-4D2F-A637-515F7C378183
// Assembly location: C:\Program Files (x86)\TRCCCAPEN\TRCC.exe

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using TRCC.Properties;

#nullable disable
namespace TRCC.DCUserControl;

public class UCDongHuaLianDong : UserControl
{
  private IContainer components = (IContainer) null;
  private Button buttonOnOff;
  private Button buttonM1;
  private Button buttonM2;
  private Button buttonM3;
  private Button buttonM4;
  private Button buttonM5;
  private Button buttonM6;
  private TextBox textBox1;
  private TextBox textBox2;
  private Button buttonYL1;
  private Button buttonYL2;
  private Button buttonYL3;
  private Button buttonXZ1;
  private Button buttonXZ2;
  private Button buttonXZ3;
  private Button buttonWL1;
  private Button buttonWL2;
  private Button buttonWL3;

  public UCDongHuaLianDong() => this.InitializeComponent();

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.buttonOnOff = new Button();
    this.buttonM1 = new Button();
    this.buttonM2 = new Button();
    this.buttonM3 = new Button();
    this.buttonM4 = new Button();
    this.buttonM5 = new Button();
    this.buttonM6 = new Button();
    this.textBox1 = new TextBox();
    this.textBox2 = new TextBox();
    this.buttonYL1 = new Button();
    this.buttonYL2 = new Button();
    this.buttonYL3 = new Button();
    this.buttonXZ1 = new Button();
    this.buttonXZ2 = new Button();
    this.buttonXZ3 = new Button();
    this.buttonWL1 = new Button();
    this.buttonWL2 = new Button();
    this.buttonWL3 = new Button();
    this.SuspendLayout();
    this.buttonOnOff.BackColor = Color.Transparent;
    this.buttonOnOff.BackgroundImage = (Image) Resources.P滑动开;
    this.buttonOnOff.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonOnOff.FlatAppearance.BorderSize = 0;
    this.buttonOnOff.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonOnOff.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonOnOff.FlatStyle = FlatStyle.Flat;
    this.buttonOnOff.Location = new Point(22, 24);
    this.buttonOnOff.Margin = new Padding(0);
    this.buttonOnOff.Name = "buttonOnOff";
    this.buttonOnOff.Size = new Size(18, 36);
    this.buttonOnOff.TabIndex = 613;
    this.buttonOnOff.UseVisualStyleBackColor = false;
    this.buttonM1.BackColor = Color.Transparent;
    this.buttonM1.BackgroundImage = (Image) Resources.P点选框A;
    this.buttonM1.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM1.FlatAppearance.BorderSize = 0;
    this.buttonM1.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM1.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM1.FlatStyle = FlatStyle.Flat;
    this.buttonM1.Location = new Point(240 /*0xF0*/, 30);
    this.buttonM1.Margin = new Padding(0);
    this.buttonM1.Name = "buttonM1";
    this.buttonM1.Size = new Size(14, 14);
    this.buttonM1.TabIndex = 643;
    this.buttonM1.UseVisualStyleBackColor = false;
    this.buttonM2.BackColor = Color.Transparent;
    this.buttonM2.BackgroundImage = (Image) Resources.P点选框;
    this.buttonM2.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM2.FlatAppearance.BorderSize = 0;
    this.buttonM2.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM2.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM2.FlatStyle = FlatStyle.Flat;
    this.buttonM2.Location = new Point(280, 30);
    this.buttonM2.Margin = new Padding(0);
    this.buttonM2.Name = "buttonM2";
    this.buttonM2.Size = new Size(14, 14);
    this.buttonM2.TabIndex = 644;
    this.buttonM2.UseVisualStyleBackColor = false;
    this.buttonM3.BackColor = Color.Transparent;
    this.buttonM3.BackgroundImage = (Image) Resources.P点选框;
    this.buttonM3.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM3.FlatAppearance.BorderSize = 0;
    this.buttonM3.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM3.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM3.FlatStyle = FlatStyle.Flat;
    this.buttonM3.Location = new Point(320, 30);
    this.buttonM3.Margin = new Padding(0);
    this.buttonM3.Name = "buttonM3";
    this.buttonM3.Size = new Size(14, 14);
    this.buttonM3.TabIndex = 645;
    this.buttonM3.UseVisualStyleBackColor = false;
    this.buttonM4.BackColor = Color.Transparent;
    this.buttonM4.BackgroundImage = (Image) Resources.P点选框;
    this.buttonM4.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM4.FlatAppearance.BorderSize = 0;
    this.buttonM4.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM4.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM4.FlatStyle = FlatStyle.Flat;
    this.buttonM4.Location = new Point(240 /*0xF0*/, 57);
    this.buttonM4.Margin = new Padding(0);
    this.buttonM4.Name = "buttonM4";
    this.buttonM4.Size = new Size(14, 14);
    this.buttonM4.TabIndex = 646;
    this.buttonM4.UseVisualStyleBackColor = false;
    this.buttonM5.BackColor = Color.Transparent;
    this.buttonM5.BackgroundImage = (Image) Resources.P点选框;
    this.buttonM5.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM5.FlatAppearance.BorderSize = 0;
    this.buttonM5.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM5.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM5.FlatStyle = FlatStyle.Flat;
    this.buttonM5.Location = new Point(280, 57);
    this.buttonM5.Margin = new Padding(0);
    this.buttonM5.Name = "buttonM5";
    this.buttonM5.Size = new Size(14, 14);
    this.buttonM5.TabIndex = 647;
    this.buttonM5.UseVisualStyleBackColor = false;
    this.buttonM6.BackColor = Color.Transparent;
    this.buttonM6.BackgroundImage = (Image) Resources.P点选框;
    this.buttonM6.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonM6.FlatAppearance.BorderSize = 0;
    this.buttonM6.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonM6.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonM6.FlatStyle = FlatStyle.Flat;
    this.buttonM6.Location = new Point(320, 57);
    this.buttonM6.Margin = new Padding(0);
    this.buttonM6.Name = "buttonM6";
    this.buttonM6.Size = new Size(14, 14);
    this.buttonM6.TabIndex = 648;
    this.buttonM6.UseVisualStyleBackColor = false;
    this.textBox1.BackColor = Color.Black;
    this.textBox1.BorderStyle = BorderStyle.None;
    this.textBox1.Font = new Font("微软雅黑", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
    this.textBox1.ForeColor = Color.FromArgb(180, 150, 83);
    this.textBox1.ImeMode = ImeMode.NoControl;
    this.textBox1.Location = new Point(429, 5);
    this.textBox1.MaxLength = 4;
    this.textBox1.Name = "textBox1";
    this.textBox1.Size = new Size(36, 16 /*0x10*/);
    this.textBox1.TabIndex = 649;
    this.textBox1.Text = "0";
    this.textBox1.TextAlign = HorizontalAlignment.Center;
    this.textBox2.BackColor = Color.Black;
    this.textBox2.BorderStyle = BorderStyle.None;
    this.textBox2.Font = new Font("微软雅黑", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 134);
    this.textBox2.ForeColor = Color.FromArgb(180, 150, 83);
    this.textBox2.ImeMode = ImeMode.NoControl;
    this.textBox2.Location = new Point(547, 5);
    this.textBox2.MaxLength = 4;
    this.textBox2.Name = "textBox2";
    this.textBox2.Size = new Size(36, 16 /*0x10*/);
    this.textBox2.TabIndex = 650;
    this.textBox2.Text = "0";
    this.textBox2.TextAlign = HorizontalAlignment.Center;
    this.buttonYL1.BackColor = Color.Transparent;
    this.buttonYL1.BackgroundImage = (Image) Resources.P预览动画;
    this.buttonYL1.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonYL1.FlatAppearance.BorderSize = 0;
    this.buttonYL1.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonYL1.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonYL1.FlatStyle = FlatStyle.Flat;
    this.buttonYL1.Location = new Point(363, 27);
    this.buttonYL1.Margin = new Padding(0);
    this.buttonYL1.Name = "buttonYL1";
    this.buttonYL1.Size = new Size(50, 20);
    this.buttonYL1.TabIndex = 651;
    this.buttonYL1.UseVisualStyleBackColor = false;
    this.buttonYL2.BackColor = Color.Transparent;
    this.buttonYL2.BackgroundImage = (Image) Resources.P预览动画;
    this.buttonYL2.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonYL2.FlatAppearance.BorderSize = 0;
    this.buttonYL2.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonYL2.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonYL2.FlatStyle = FlatStyle.Flat;
    this.buttonYL2.Location = new Point(481, 27);
    this.buttonYL2.Margin = new Padding(0);
    this.buttonYL2.Name = "buttonYL2";
    this.buttonYL2.Size = new Size(50, 20);
    this.buttonYL2.TabIndex = 652;
    this.buttonYL2.UseVisualStyleBackColor = false;
    this.buttonYL3.BackColor = Color.Transparent;
    this.buttonYL3.BackgroundImage = (Image) Resources.P预览动画;
    this.buttonYL3.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonYL3.FlatAppearance.BorderSize = 0;
    this.buttonYL3.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonYL3.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonYL3.FlatStyle = FlatStyle.Flat;
    this.buttonYL3.Location = new Point(599, 27);
    this.buttonYL3.Margin = new Padding(0);
    this.buttonYL3.Name = "buttonYL3";
    this.buttonYL3.Size = new Size(50, 20);
    this.buttonYL3.TabIndex = 653;
    this.buttonYL3.UseVisualStyleBackColor = false;
    this.buttonXZ1.BackColor = Color.Transparent;
    this.buttonXZ1.BackgroundImage = (Image) Resources.P载入动画;
    this.buttonXZ1.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonXZ1.FlatAppearance.BorderSize = 0;
    this.buttonXZ1.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonXZ1.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonXZ1.FlatStyle = FlatStyle.Flat;
    this.buttonXZ1.Location = new Point(363, 54);
    this.buttonXZ1.Margin = new Padding(0);
    this.buttonXZ1.Name = "buttonXZ1";
    this.buttonXZ1.Size = new Size(50, 20);
    this.buttonXZ1.TabIndex = 654;
    this.buttonXZ1.UseVisualStyleBackColor = false;
    this.buttonXZ2.BackColor = Color.Transparent;
    this.buttonXZ2.BackgroundImage = (Image) Resources.P载入动画;
    this.buttonXZ2.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonXZ2.FlatAppearance.BorderSize = 0;
    this.buttonXZ2.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonXZ2.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonXZ2.FlatStyle = FlatStyle.Flat;
    this.buttonXZ2.Location = new Point(481, 54);
    this.buttonXZ2.Margin = new Padding(0);
    this.buttonXZ2.Name = "buttonXZ2";
    this.buttonXZ2.Size = new Size(50, 20);
    this.buttonXZ2.TabIndex = 655;
    this.buttonXZ2.UseVisualStyleBackColor = false;
    this.buttonXZ3.BackColor = Color.Transparent;
    this.buttonXZ3.BackgroundImage = (Image) Resources.P载入动画;
    this.buttonXZ3.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonXZ3.FlatAppearance.BorderSize = 0;
    this.buttonXZ3.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonXZ3.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonXZ3.FlatStyle = FlatStyle.Flat;
    this.buttonXZ3.Location = new Point(599, 54);
    this.buttonXZ3.Margin = new Padding(0);
    this.buttonXZ3.Name = "buttonXZ3";
    this.buttonXZ3.Size = new Size(50, 20);
    this.buttonXZ3.TabIndex = 656;
    this.buttonXZ3.UseVisualStyleBackColor = false;
    this.buttonWL1.BackColor = Color.Transparent;
    this.buttonWL1.BackgroundImage = (Image) Resources.P网络按钮;
    this.buttonWL1.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonWL1.FlatAppearance.BorderSize = 0;
    this.buttonWL1.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonWL1.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonWL1.FlatStyle = FlatStyle.Flat;
    this.buttonWL1.Location = new Point(418, 54);
    this.buttonWL1.Margin = new Padding(0);
    this.buttonWL1.Name = "buttonWL1";
    this.buttonWL1.Size = new Size(20, 20);
    this.buttonWL1.TabIndex = 657;
    this.buttonWL1.UseVisualStyleBackColor = false;
    this.buttonWL2.BackColor = Color.Transparent;
    this.buttonWL2.BackgroundImage = (Image) Resources.P网络按钮;
    this.buttonWL2.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonWL2.FlatAppearance.BorderSize = 0;
    this.buttonWL2.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonWL2.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonWL2.FlatStyle = FlatStyle.Flat;
    this.buttonWL2.Location = new Point(536, 54);
    this.buttonWL2.Margin = new Padding(0);
    this.buttonWL2.Name = "buttonWL2";
    this.buttonWL2.Size = new Size(20, 20);
    this.buttonWL2.TabIndex = 658;
    this.buttonWL2.UseVisualStyleBackColor = false;
    this.buttonWL3.BackColor = Color.Transparent;
    this.buttonWL3.BackgroundImage = (Image) Resources.P网络按钮;
    this.buttonWL3.BackgroundImageLayout = ImageLayout.Stretch;
    this.buttonWL3.FlatAppearance.BorderSize = 0;
    this.buttonWL3.FlatAppearance.MouseDownBackColor = Color.Transparent;
    this.buttonWL3.FlatAppearance.MouseOverBackColor = Color.Transparent;
    this.buttonWL3.FlatStyle = FlatStyle.Flat;
    this.buttonWL3.Location = new Point(654, 54);
    this.buttonWL3.Margin = new Padding(0);
    this.buttonWL3.Name = "buttonWL3";
    this.buttonWL3.Size = new Size(20, 20);
    this.buttonWL3.TabIndex = 659;
    this.buttonWL3.UseVisualStyleBackColor = false;
    this.AutoScaleMode = AutoScaleMode.Inherit;
    this.BackColor = Color.Transparent;
    this.BackgroundImage = (Image) Resources.P01动画联动;
    this.Controls.Add((Control) this.buttonWL3);
    this.Controls.Add((Control) this.buttonWL2);
    this.Controls.Add((Control) this.buttonWL1);
    this.Controls.Add((Control) this.buttonXZ3);
    this.Controls.Add((Control) this.buttonXZ2);
    this.Controls.Add((Control) this.buttonXZ1);
    this.Controls.Add((Control) this.buttonYL3);
    this.Controls.Add((Control) this.buttonYL2);
    this.Controls.Add((Control) this.buttonYL1);
    this.Controls.Add((Control) this.textBox2);
    this.Controls.Add((Control) this.textBox1);
    this.Controls.Add((Control) this.buttonM6);
    this.Controls.Add((Control) this.buttonM5);
    this.Controls.Add((Control) this.buttonM4);
    this.Controls.Add((Control) this.buttonM3);
    this.Controls.Add((Control) this.buttonM2);
    this.Controls.Add((Control) this.buttonM1);
    this.Controls.Add((Control) this.buttonOnOff);
    this.DoubleBuffered = true;
    this.Margin = new Padding(0);
    this.Name = nameof (UCDongHuaLianDong);
    this.Size = new Size(682, 84);
    this.ResumeLayout(false);
    this.PerformLayout();
  }
}
